jobs:
  regCenter:
    serverList: "localhost:2181"
    namespace: luffy-cloud-elastic-job
  instances:
    - name: some-job
      # 每天1点生成前一天的数据
      #      cron: 0 0 1 * * ?
      # 每三秒执行一次
      cron: "0/3 * * * * ?"
      #两个作业分片
      shardingTotalCount: 2
      #even执行设备编号为偶数的设备
      shardingItemParameters: 0=even,1=odd
      jobDescription: "设备纬度日报"
      jobParameter:
    - name: insert-payment-job
      # 每天1点生成前一天的数据
      #      cron: 0 0 1 * * ?
      # 每20秒执行一次
      cron: "0/20 * * * * ?"
      #作业分片
      shardingTotalCount: 1
      shardingItemParameters: 0=even
      jobDescription: "给payment表增加数据"
      jobParameter:
